version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - reminderly-network

  app:
    build: .
    container_name: scheduler-service
    restart: always
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: 6379
    ports:
      - "8081:8081"
    networks:
      - reminderly-network

volumes:
  redis_data:
    driver: local

networks:
  reminderly-network:
    external: true